# Generated by Django 2.0.6 on 2018-06-08 11:46

import django.core.validators
from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_floodmappage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floodmappage',
            name='filters',
        ),
        migrations.AddField(
            model_name='floodmappage',
            name='country',
            field=models.CharField(blank=True, choices=[('us', 'United States'), ('pl', 'Poland'), ('sk', 'Slovakia'), ('it', 'Italy'), ('ua', 'Ukraine'), ('ru', 'Russia'), ('kz', 'Kazakhstan')], help_text='countries', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='floodmappage',
            name='flood_prob_threshold',
            field=models.FloatField(default=0.6, help_text='flood probability threshold', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='floodmappage',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'Français'), ('es', 'Español'), ('de', 'Deutsch')], help_text='languages', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='floodmappage',
            name='time_range_picker',
            field=wagtail.core.fields.StreamField([('time_range_picker', wagtail.core.blocks.StructBlock([('date_from', wagtail.core.blocks.DateBlock()), ('time_from', wagtail.core.blocks.TimeBlock()), ('date_to', wagtail.core.blocks.DateBlock()), ('time_to', wagtail.core.blocks.TimeBlock())]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodmappage',
            name='time_range_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
