# Generated by Django 2.0.6 on 2018-06-08 14:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180608_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floodmappage',
            name='time_range_picker',
        ),
        migrations.AddField(
            model_name='floodmappage',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='floodmappage',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='floodmappage',
            name='time_from',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='floodmappage',
            name='time_to',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
