# Generated by Django 2.0.6 on 2018-06-12 16:00

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180612_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodmappage',
            name='country',
            field=models.CharField(blank=True, choices=[('us', 'United States'), ('pl', 'Poland'), ('sk', 'Slovakia'), ('it', 'Italy'), ('ua', 'Ukraine'), ('ru', 'Russia'), ('kz', 'Kazakhstan')], help_text='countries', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='floodmappage',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='floodmappage',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='floodmappage',
            name='flood_prob_threshold',
            field=models.FloatField(default=0.6, help_text='flood probability threshold', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='floodmappage',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'Français'), ('es', 'Español'), ('de', 'Deutsch')], help_text='languages', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='floodmappage',
            name='time_from',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='floodmappage',
            name='time_range_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='floodmappage',
            name='time_to',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
