# Generated by Django 2.0.6 on 2018-06-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180612_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floodmappage',
            old_name='date_from',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='floodmappage',
            old_name='date_to',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='floodmappage',
            name='country',
        ),
        migrations.RemoveField(
            model_name='floodmappage',
            name='flood_prob_threshold',
        ),
        migrations.RemoveField(
            model_name='floodmappage',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='floodmappage',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='floodmappage',
            name='time_range_text',
        ),
        migrations.RemoveField(
            model_name='floodmappage',
            name='time_to',
        ),
    ]
