# Generated by Django 2.0.6 on 2018-06-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0008_auto_20180612_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floodmappage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='FloodMapPage',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
